name: Orbital Art
favicon: null
layout_spectrum: 0.3593939603306353
typography_spectrum: 0.8292013925965875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4507375059183687
  lightness: 0.8786732212174684
  saturation: 0.4018261255696416
  rhythmicContrast: 0.14561068965122104
purpose: []
